# Generated by Django 4.1 on 2022-08-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=200, unique=True)),
                ('poster_url', models.TextField(default='default')),
                ('rating_aud', models.CharField(max_length=10, null=True)),
                ('rating_cri', models.CharField(max_length=10, null=True)),
                ('rating_net', models.CharField(max_length=10, null=True)),
                ('genre', models.CharField(default='default', max_length=200)),
                ('showtimes', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('rate', models.CharField(default='default', max_length=200)),
                ('summary', models.TextField(default='default')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image_url', models.TextField(default='default')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
